// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7O9tNCsG0SqTjrlip0O5Uwk_IBegLBRk',
    appId: '1:210151196614:web:0d8caa72f0afae334694c7',
    messagingSenderId: '210151196614',
    projectId: 'servlocate-firebase-1',
    authDomain: 'servlocate-firebase-1.firebaseapp.com',
    storageBucket: 'servlocate-firebase-1.firebasestorage.app',
    measurementId: 'G-ZFH5CDNWXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACAf6gbO8ohZJFiepFl8K5QMQqQkJb42g',
    appId: '1:210151196614:android:2a5b14a9d2d876e14694c7',
    messagingSenderId: '210151196614',
    projectId: 'servlocate-firebase-1',
    storageBucket: 'servlocate-firebase-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSoUM2zlx8BOy1hfXSSrGwIcONmmW_DjI',
    appId: '1:210151196614:ios:681df09f8ce865684694c7',
    messagingSenderId: '210151196614',
    projectId: 'servlocate-firebase-1',
    storageBucket: 'servlocate-firebase-1.firebasestorage.app',
    iosBundleId: 'com.example.servlocateApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSoUM2zlx8BOy1hfXSSrGwIcONmmW_DjI',
    appId: '1:210151196614:ios:681df09f8ce865684694c7',
    messagingSenderId: '210151196614',
    projectId: 'servlocate-firebase-1',
    storageBucket: 'servlocate-firebase-1.firebasestorage.app',
    iosBundleId: 'com.example.servlocateApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7O9tNCsG0SqTjrlip0O5Uwk_IBegLBRk',
    appId: '1:210151196614:web:4cfc8f00d52ab93b4694c7',
    messagingSenderId: '210151196614',
    projectId: 'servlocate-firebase-1',
    authDomain: 'servlocate-firebase-1.firebaseapp.com',
    storageBucket: 'servlocate-firebase-1.firebasestorage.app',
    measurementId: 'G-V2WC2QMV5H',
  );
}
